framework:
  workflows:
    article:
      type: workflow
      marking_store:
        type: method
      supports:
        - App\Entity\Article
      places:
        draft:
          metadata:
            title: Draft
        waiting for journalist:
          metadata:
            title: Waiting for Journalist review
        approved by journalist:
          metadata:
            title: Approved By Journalist
        wait for spellchecker:
          metadata:
            title: Waiting for Spellchecker review
        approved by spellchecker:
          metadata:
            title: Approved By Spellchecker
        published: ~
      transitions:
        request review:
          guard: "is_fully_authenticated()"
          from: draft
          to:
            - waiting for journalist
            - wait for spellchecker
          metadata:
            title: Do you want a Review?
        journalist approval:
          guard: "is_granted('ROLE_JOURNALIST')"
          from: waiting for journalist
          to: approved by journalist
          metadata:
            title: Do you valid the article?
