##survos_workflow_bundle:
##    resource: '@SurvosWorkflowBundle/Controller/WorkflowController.php'
##    # resource: '@EasyAdminBundle/Controller/AdminController.php'
##    prefix: /workflow
##    type: annotation
#
#survos_workflows: {path: /, controller: 'Survos\WorkflowBundle\Controller\WorkflowController::workflows'}
#survos_workflow: {path: "/workflow/{flowCode}", controller: 'Survos\WorkflowBundle\Controller\WorkflowController::workflow'}
